### ISSUE TITLE
Problem loading the file hikaricp.prod.properties

### ISSUE THREAD

**Issue by ochsenius** [edulify/play-hikaricp.edulify.com#35]
I had a problem loading the configuration file of Hikari. This only happens when I set up with Shell, not the play console.

The configuration suggest adding in the application.conf
db.default.hikaricp.file = "conf/hikaricp.prod.properties"

Which is fine, but via shell I get an error stating:

[Loading from file configured by db.default.hikaricp.file That Is Some ("conf/hikaricp.prod.properties")]

If you strip the quotes to the configuration file, then it works fine for command line and Shell.
=> db.default.hikaricp.file = conf/hikaricp.prod.properties

**Comment by megazord** [comment]
Hello, First of all, sorry for the long time to answer your question. 

This is not an error message, but just a simple log to help you to debug any problems you could have.
