### ISSUE TITLE
Dynamically translate typesafe HOCON properties to Hikari properties

### ISSUE THREAD

**Issue by dkharrat** [edulify/play-hikaricp.edulify.com#36]
I'm trying out this plugin and noticed that the preferred way to use it is to reference a properties file in the app's .conf file. In our particular application, we have references to many databases (over 16). I feel that defining a property file for each database is a bit messy and will lead to many files. Ideally, I'd like to have the configuration for our databases all defined in one file (production.conf) using the HOCON syntax.

I could use the Play way of defining the config, but the issue is that I'm limited to what Play defines. Why be constrained to what Play defines? Would it be possible to allow using the actual Hikari properties, and just pass them to the `HikariConfig` object as is (could be done by getting the property names of the hikari's hocon subtree dynamically).

e.g.
```
db.default.hikaricp {
  dataSourceClassName="org.postgresql.ds.PGSimpleDataSource"
  dataSource.user=test
  dataSource.password=secret
  dataSource.databaseName=mydb
  dataSource.serverName=localhost
}
```

**Comment by megazord** [comment]
Fixed at master branch.
