### ISSUE TITLE
How to use Hikaricp with Slick 2.1?

### ISSUE THREAD

**Issue by satybald** [edulify/play-hikaricp.edulify.com#37]
I'd like to use Hickaricp with Slick in play 2.3.3. I've configured the app regarding the instruction:
Step1
```
  "com.edulify" %% "play-hikaricp" % "1.5.0",
  "com.typesafe.play" %% "play-slick" % "0.8.0" exclude("com.jolbox","bonecp"),
  "mysql" % "mysql-connector-java" % "5.1.32",
```
Step 2: Disable default dbplugin

Step3:
```
200:com.edulify.play.hikaricp.HikariCPPlugin
1500:com.typesafe.plugin.CommonsMailerPlugin
```

Step4:
db.default.hikaricp.file="conf/hikaricp.properties"
```
dbplugin=disabled

# Slick Evolutions
# ~~~~~
slick.default="models.*"

with hikaricp.properties:
dataSourceClassName=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
dataSource.user=logex
dataSource.url=jdbc:mysql://localhost:3306/logex
dataSource.password=
#maxLifetime=900000
#idleTimeout=300000
#maximumPoolSize=20
#minimumIdle=5
```
However, when I'm running the app I get the following error:
```
Configuration error: Configuration error[Slick error : jdbc driver not defined in application.conf for db.default.driver key
```

I have to specify in application.conf following to make app working:
```
db.default.driver=com.mysql.jdbc.Driver
db.default.url="jdbc:mysql://localhost:3306/logex"
```
But it seem that Slick is not using Hikaricp and use old BoneCP with play. I'm wondering how would be a proper way to customize slick with hikaricp?

**Comment by janlisse** [comment]
I experience the same error using play-hikaricp 2.0.1 and play-slick 0.8.1.
I'm also using MySQL and the config matches the one in the docs.

**Comment by megazord** [comment]
The commit above documents how to use this plugin with play-slick 0.8.1. When using `play.api.db.slick.DB.withSession` play-slick is smart enough to use the configured pool, instead of opening connections by itself. Also, since `dbplugin` is disabled, it won't use BoneCP.
