### ISSUE TITLE
Get rid of "jdbcConnectionTest" warning when using Play configuration

### ISSUE THREAD

**Issue by studiodev** [edulify/play-hikaricp.edulify.com#40]
When HikariCP is configured through play `application.conf`, a warning is always displayed in the console.

    [warn] c.z.h.HikariConfig - The jdbcConnectionTest property is now deprecated, see the
    documentation for connectionTestQuery

This warning is triggered when the [`jdbc4ConnectionTest`](https://github.com/brettwooldridge/HikariCP/blob/2e24d8425f0a736ea6d1a7ff2c290278fff6d5bd/hikaricp-common/src/main/java/com/zaxxer/hikari/AbstractHikariConfig.java#L479) property is setted

It's not possible to remove this warning by tweaking play configuration, due to [this line](https://github.com/edulify/play-hikaricp.edulify.com/blob/master/module-code/app/com/edulify/play/hikaricp/HikariCPConfig.scala#L76) which always set this property.

**Comment by megazord** [comment]
Yes, you are right.

I have plans to remove all configuration options in favor of have Hikari configured directly in `application.conf` file. In other words, we won't have this translation between Play properties and Hikari. I expect to work on that the next days.

**Comment by studiodev** [comment]
Yes it seems a good plan. It's easier to inject a custom config in tests with the Play configuration than Hikari properties.

**Comment by megazord** [comment]
Fixed at master branch.
