### ISSUE TITLE
Version 2.0.2 with JAVA 7

### ISSUE THREAD

**Issue by deanzz** [edulify/play-hikaricp.edulify.com#58]
Hi, 

I want to use version 2.0.2 with JAVA 7,
what should I do?

Thanks
Dean

**Comment by megazord** [comment]
Version 1.5.2 is the last stable release that supports Java 7. But you can easily build this plugin using Java 7. Here is what you need to do:

1. Replace the [HikariCP dependency](https://github.com/edulify/play-hikaricp.edulify.com/blob/master/build.sbt#L13) with the version that supports Java 6/7 (please, see [HikariCP docs](http://brettwooldridge.github.io/HikariCP/))
2. Run `make publish-local` (or the commands listed in `Makefile`) to generate a new version.
3. Use that new version.

**Comment by johdah** [comment]
Why ditch the support for java 7?
