### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mberndt123** [edulify/play-hikaricp.edulify.com#62]
I recently submitted this pull request:
https://github.com/edulify/play-hikaricp.edulify.com/pull/60

I made this change hoping that I would be able to use it, but there hasn't been a release since. Can you please make a release?

**Comment by megazord** [comment]
Yes! And I'm sorry.

I will do a new release today.

**Comment by megazord** [comment]
@mberndt123 version 2.0.4 was just released. 

Thanks for the PR and sorry for the long delay.

**Comment by mberndt123** [comment]
Thanks
