### ISSUE TITLE
com/zaxxer/hikari/HikariConfig : Unsupported major.minor version 52.0 with Java 7

### ISSUE THREAD

**Issue by barbolani** [edulify/play-hikaricp.edulify.com#64]
Following the provided instructions produces this error under Java 7. I see that the Hikari team has provided some mechanism to work around this issue

However, for those not that much versed in Maven or sbt, could you provide some guidance as to how to workaround in the plugin?

**Comment by megazord** [comment]
@barbolani 

Since version 2.0.0 we are supporting just Java 8. If there are enough users that require Java 7 support, I will probably reverse that decision. Until now, I get just a few comments. Anyway, you can see [how to build this plugin to Java 7 here](https://github.com/edulify/play-hikaricp.edulify.com/issues/58#issuecomment-82729702).

**Comment by barbolani** [comment]
Thanks for your response. And apologies in advance because I'm a novice in the sbt/maven arena. I cloned the git repo at play-hikaricp.edulify.com , changed the build.sbt so that it looks like

libraryDependencies ++= Seq(
  jdbc,
  "com.zaxxer" % "HikariCP-java6" % "2.3.6",
  "com.googlecode.usc" % "jdbcdslog" % "1.0.6.2",
  "com.h2database" % "h2" % "1.4.186" % "test"
)

And did a clean/compile, which apparently completed without errors. Now what I have to do to use the Java-7 built version instead of the default one in my Play app?

**Comment by lekhrajprasad** [comment]
could you please provide the link of version 2.0.0

**Comment by marcospereira** [comment]
Hi @lekhrajprasad, here is the docs for version 2.0.0:

https://github.com/edulify/play-hikaricp.edulify.com/blob/2.0.0/README.md

If you are still using Play 2.3, it is recommended that you use version 2.0.6 of this plugin:

https://github.com/edulify/play-hikaricp.edulify.com/blob/2.0.6/README.md
