### ISSUE TITLE
Config translation for JDBC connection settings

### ISSUE THREAD

**Issue by takezoe** [edulify/play-hikaricp.edulify.com#65]
Config translation was removed at https://github.com/edulify/play-hikaricp.edulify.com/commit/ffcbc78a3762709ef3280b9a05aa64a86ab6648d. However I think it causes duplicated configuration if we use play-hikaricp with other plugins such as [flyway-play](https://github.com/flyway/flyway-play) because they expect default Play2 configuration.

```
# for play-hikaricp
dbplugin=disabled
db.default.driverClassName=com.mysql.jdbc.Driver
db.default.jdbcUrl="jdbc:mysql://localhost:3306/test"
db.default.username=root
db.default.password=""

# for flyway-play
db.default.driver=com.mysql.jdbc.Driver
db.default.url="jdbc:mysql://localhost:3306/test"
db.default.user=root
```

Therefore I think it's useful to provide translation for basic JDBC connection settings.

**Comment by megazord** [comment]
Sounds good to me, @takezoe. Could you please send a PR for this?

We could probably copy the code from Playframework itself now (version 2.4 will support HikariCP out-of-the box).

**Comment by takezoe** [comment]
I sent a pull request #66

**Comment by megazord** [comment]
PR was merged. I will close this issue after releasing a new version.

Thanks, @takezoe.

**Comment by takezoe** [comment]
@megazord Thanks! I'm looking forward to the next release. We really need it.

**Comment by megazord** [comment]
@takezoe version 2.0.5 released here:

https://github.com/edulify/play-hikaricp.edulify.com/releases/tag/2.0.5

Thanks again.
