### ISSUE TITLE
Play 2.2.2 with play hikari plugin 1.0.0 not working

### ISSUE THREAD

**Issue by lalkhum** [edulify/play-hikaricp.edulify.com#67]
I am using Play 2.2.2 version and I followed the instruction details as specified in Readme.
My scala version being 2.10, still I got the following error.

com.edulify#play-hirakicp_2.10;1.0.0: not found

Also got anoother error which is

<pre><span class="line">&nbsp;</span><span class="code">    com.edulify.play.hikaricp.HikariCPConfig.maxPoolSize(HikariCPConfig.scala:81)</span></pre>
			        
						<pre><span class="line">&nbsp;</span><span class="code">    com.edulify.play.hikaricp.HikariCPConfig.mapFromPlayConfiguration(HikariCPConfig.scala:65)</span></pre>		        
						<pre><span class="line">&nbsp;</span><span class="code">    com.edulify.play.hikaricp.HikariCPConfig.getHikariConfig(HikariCPConfig.scala:31)</span></pre>		        
						<pre><span class="line">&nbsp;</span><span class="code">    com.edulify.play.hikaricp.HirakiCPDBApi$$anonfun$1.apply(HirakiCPDBApi.scala:34)</span></pre>
						<pre><span class="line">&nbsp;</span><span class="code">    com.edulify.play.hikaricp.HirakiCPDBApi$$anonfun$1.apply(HirakiCPDBApi.scala:32)</span></pre>

Any help appreciated.

**Comment by megazord** [comment]
Unfortunately the version 1.0.0 was not was not build with Scala 2.10 support. I think that is something we could do and will investigate it later.

**Comment by megazord** [comment]
Actually, it was build with scala 2.10 also. Did you add the Edulify repository to your build?

**Comment by lalkhum** [comment]
@megazord Actually, I figured out a way to configure up my Play 2.2.2 with scala 2.10 support by having created a file called "hikaricp config file" that stores the database details as follows.
1. In my play conf environment "dev.conf", I need the following line.
db.default.hikaricp.file="conf/environments/hikaricp.dev.properties"
2. The "conf/environments/hikaricp.dev.properties" file now contains 
{code}
jdbcUrl=somejdbcUrl
username=someuser
password=***
{code}

However, it is not able to pick up the default play config details as specified in the release note. My approach as above seems to be the only-working solution for this.

**Comment by megazord** [comment]
Could you try with version 1.2.0 of  the plugin? This is the last version that is binary compatible with Play 2.2.x.

**Comment by lalkhum** [comment]
Yes, I tried and it is working perfectly for me. Btw, I think it would be nice to add an extra column about the link to release notes/info in your play version support table(?)

**Comment by megazord** [comment]
Good idea. Do you mind submitting a PR with this change?

**Comment by lalkhum** [comment]
Yup sure. Could you give me access for the PR?

**Comment by megazord** [comment]
Merged. :-)

Thank you very much, @lalkhum.
