### ISSUE TITLE
Cannot use logSql with JNDI

### ISSUE THREAD

**Issue by sebdotv** [edulify/play-hikaricp.edulify.com#70]
When accessing the datasource through JNDI (for example using JPA), `logSql` seems to be ignored and no logging happens. Apparently, the datasource that is bound to JNDI is always the one without logging:
https://github.com/edulify/play-hikaricp.edulify.com/blob/master/app/com/edulify/play/hikaricp/HikariCPDBApi.scala#L53

**Comment by megazord** [comment]
@sebdotv, you are right. Do you mind submitting a pull request to fix this issue?
