### ISSUE TITLE
Hikaricp metricRegistry definition

### ISSUE THREAD

**Issue by remk** [edulify/play-hikaricp.edulify.com#74]
Is there a way to define the hikariCp "metricRegistry" configuration with this plugin ?
And if so, which is the prefered way ?

**Comment by marcospereira** [comment]
There is not. According to HikariCP docs "this property is only available via programmatic configuration or IoC container".

But I think we can make this configurable if the MetricRegistry is simple enough. 

Do you want to submit a PR?

**Comment by remk** [comment]
Thanks for your response.
I solved my issue using the log of connections leaks.
I will not have the time to make a PR.
